.TH B 1
.SH NAME
sdb \- stardict browser
.SH SYNOPSIS
.B b
[
.B -c
.I dir
]
[
.B -d
.I dict
]
[
.B -alsu
]
[
.B --
]
[
.I pattern
]
.SH DESCRIPTION
.I SDB
is a stardict browser.
If a
.I pattern
is given on the command line,
.I b
prints all matching entries;
otherwise it repeatedly accepts once a line as pattern.
The options are
.TP
.BI -c " dir"
Use dictionaries in given dir.
.TP
.BI -d " dict"
Use the given dictionary.
.TP
.B -a
Accurate accent matching (disable Latin-1 accent folding).
.TP
.B -l
Print a list of available dictionaries.
.TP
.B -s
Strict case matching (disable case-insensitive search).
.TP
.B -u
Unicode case folding.
.TP
.B --
Stop option parsing.
.SH FILES
.B $XDG_DATA_HOME/stardict/dic
.br
.B /usr/lib/stardict/dic
.SH "SEE ALSO"
.IR sdcv (1)
.SH BUGS
Do not handle regexp, html.
.br
Do not support dict larger than 4GiB
.br
Do not support image, audio or multiple text sametypesequence.
