.TH B 1
.SH NAME
sdb \- stardict browser
.SH SYNOPSIS
.B b
[
.B -c
.I dir
]
[
.B -d
.I dict
]
[
.B -afl
]
[
.B --
]
[
.I pattern
]
.SH DESCRIPTION
.I SDB
is a stardict browser.
If a
.I pattern
is given on the command line,
.I b
prints all matching entries;
otherwise it repeatedly accepts once a line as pattern.
The options are
.TP
.BI -c " dir"
Use dictionaries in given dir.
.TP
.BI -d " dict"
Use the given dictionary.
A list of available dictionaries is printed by
.BR -d .
.TP
.B -a
Suppress latin1 accent fold of pattern.
.TP
.B -f
Suppress ASCII case fuzzy match of pattern.
.TP
.B -l
Do unicode case fold of pattern.
.TP
.B --
Stop option parsing.
.SH FILES
.B $XDG_DATA_HOME/stardict/dic
.br
.B /usr/lib/stardict/dic
.SH "SEE ALSO"
.IR sdcv (1)
.SH BUGS
Do not handle dictzip, you should gunzip .dict.dz to .dict.
.br
Do not handle regexp, html.
.br
Do not support dict larger than 4GiB
.br
Do not support image, audio or multiple text sametypesequence.
.br
Segfault when a lot -ddict supplied, change dflag = bufoff if need .
