.TH B 1
.SH NAME
sdb \- stardict browser
.SH SYNOPSIS
.B sdb
[
.B -c
.I dir
]
[
.B -d
.I dict
]
[
.B -alrsuD
]
[
.B --
]
[
.I pattern
]
.SH DESCRIPTION
.I SDB
is a stardict browser.
If a
.I pattern
is given on the command line,
.I sdb
prints all matching entries;
otherwise it repeatedly accepts once a line as pattern.
The options are
.TP
.BI -c " dir"
Use dictionaries in given dir.
.TP
.BI -d " dict"
Use the given dictionary.
.TP
.B -a
Accurate accent matching.
.TP
.B -l
Print a list of available dictionaries.
.TP
.B -r
Use regex matching.
.TP
.B -s
Strict case matching.
.TP
.B -u
Unicode case lowercasing.
.TP
.B -D
Disable html rendering.
.TP
.B --
Stop option parsing.
.SH FILES
.B $XDG_DATA_HOME/stardict/dic
.br
.B /usr/share/stardict/dic
.SH "SEE ALSO"
.IR sdcv (1)
